server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: lingpao123
eureka:
  client:
#    是否将自己注册进eureka server,默认为true
    register-with-eureka: true
#    是否从eureka server抓取已有的注册信息,默认为true
#    单节点无所谓,集群必须设置为true,才能配合ribbon使用负载均衡
    fetch-registry: true
#    service-url配置内容是map类型的,所以配置信息必须为key: value形式
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/
      #集群
      #只向一个服务注册中心注册,eureka集群之间可以相互复制,所以每个注册中心都可以看到
      #但是为了避免该服务注册中心刚好挂掉,保险起见,需要向多个服务注册中心注册
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/